postgresql:
  image: docker.molflow.com/odin_db:latest
  ports:
    - 5432:5432
#  environment:
#    - POSTGRES_PASSWORD:test

webapi:
  image: docker.molflow.com/odin_redo/odin_api:latest
  ports: 
    - 5000:5000
  volumes:
    - src/:/app
  links:
    - postgresql
