version: '3.4'

services:
  postgresql:
    image: docker2.molflow.com/odin_redo/odin_db:latest
    ports:
      - 5432:5432
    restart: unless-stopped

  httpd:
    build: ./services/proxy
    ports:
      - 5000:80
    links:
      - webapi
    volumes:
      - ./services/proxy/testdata/:/data/odin-l2-data/:ro
    restart: unless-stopped

  webapi:
    environment:
      - PGHOST=postgresql
      - PGDBNAME=odin
      - PGUSER=odinop
      - PGPASS=odinop
    build: .
    volumes:
      - ./src/:/app:ro
      - ./data/vds-data:/vds-data:ro
      - ./data/apriori:/var/lib/odindata/apriori:ro
      - ./data/vds-data/SMRhdf/Qsmr-2-1/:/odin-smr-2-1-data:ro
      - ./data/ptz-data/:/var/lib/odindata:rw
      - ./data/vds-data/OSIRIS_Level2/:/osiris-data:ro
      - ./data/ptz-data/ERA-Interim:/var/lib/odindata/ECMWF:rw
      - ./data/odin-l2-data:/data/odin-l2-data:rw
    links:
      - postgresql
      - level2db
    restart: unless-stopped

  level2db:
    image: mongo
    restart: unless-stopped
