postgresql:
  image: docker.molflow.com/odin_db:latest
  ports:
    - 5432:5432
#  environment:
#    - POSTGRES_PASSWORD:test

webapi:
  image: cb2231687051
  ports: 
    - 5000:5000
  volumes:
    - src/:/app 
    - /home/bengt/test/data/:/var/lib/odindata
  links:
    - postgresql
