version: '3.4'

services:
  postgresql:
    image: odinsmr/odin_db:latest
    ports: ["5432"]

  odin:
    build: ./services/proxy
    ports: ["80"]
    links:
      - webapi
    volumes:
      - ./services/proxy/testdata/:/data/odin-l2-data/:ro

  webapi:
    environment:
      - PGHOST=postgresql
      - PGDBNAME=odin
      - PGUSER=odinop
      - PGPASS=odinop
    build:
      context: .
      dockerfile: Dockerfile
    image: odinsmr/odin_api
    volumes:
      - ./src/:/app:ro
      - ./data/vds-data:/vds-data:ro
      - ./data/vds-data/SMRhdf/Qsmr-2-1/:/odin-smr-2-1-data:ro
      - ./data/vds-data/OSIRIS_Level2/:/osiris-data:ro
      - ./data/apriori:/var/lib/odindata/apriori:ro
      - ./data/ptz-data/Solardata2.db:/var/lib/odindata/Solardata2.db:ro
      - ./data/ptz-data/ERA-Interim:/var/lib/odindata/ECMWF:ro
    depends_on:
      - postgresql
      - level2db

  level2db:
    image: mongo
    ports: ["27017"]
