postgresql:
  image: docker2.molflow.com/odin_rerun/odin_db:latest
  ports:
    - 5432:5432
#  environment:
#    - POSTGRES_PASSWORD:test

webapi:
  image: docker2.molflow.com/odin_rerun/odin_api:latest
  ports:
    - 5000:5000
  volumes:
    - src/:/app
    - data/:/var/lib/odindata
  links:
    - postgresql
