postgresql:
  image: docker2.molflow.com/odin_redo/odin_db:latest
  ports:
    - 5432:5432
#  environment:
#    - POSTGRES_PASSWORD:test

webapi:
  image: docker2.molflow.com/odin_redo/odin_api:latest
  ports:
    - 5000:5000
  volumes:
    - ./src/:/app
    - ./data/:/var/lib/odindata
    - /home/skymandr/Documents/Work/ODIN/odin_redo_documents/VDS/QSMR2.1_test:/odin-smr-2-1-data
  links:
    - postgresql
