postgresql:
  image: docker2.molflow.com/odin_redo/odin_db:latest
  ports:
    - 5432:5432

webapi:
  build: .
  ports:
    - 5000:5000
  volumes:
    - ./src/:/app
    - ./data/vds-data/:/vds-data
  links:
    - postgresql
    - level2db

level2db:
  image: mongo
