postgresql:
  image: docker2.molflow.com/odin_redo/odin_db:latest
  ports:
    - 5432:5432

httpd:
  build: ./services/proxy
  ports:
    - 5000:80
  links:
    - webapi
  volumes:
    - ./services/proxy/testdata/:/data/odin-l2-data/

webapi:
  environment:
    - PGHOST=postgresql
    - PGDBNAME=odin
    - PGUSER=odinop
    - PGPASS=odinop
  build: .
  volumes:
    - ./src/:/app
    - ./data/vds-data:/vds-data
    - ./data/apriori:/var/lib/odindata/apriori
    - ./data/vds-data/SMRhdf/Qsmr-2-1/:/odin-smr-2-1-data
    - ./data/ptz-data/:/var/lib/odindata
    - ./data/vds-data/OSIRIS_Level2/:/osiris-data
    - ./data/ptz-data/ERA-Interim:/var/lib/odindata/ECMWF
    - ./data/odin-l2-data:/data/odin-l2-data    
  links:
    - postgresql
    - level2db

level2db:
  image: mongo
