FROM mcr.microsoft.com/devcontainers/python:3.11

# Install Node 20 (recommended)
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
  && apt-get update \
  && apt-get install -y nodejs \
  && node -v && npm -v && npx -v